version: '3.8'


services:
  astro-app:
    image: kkr-rppi-project:latest
    container_name: kkrppi
    restart: always
    ports:
      - "5476:4321"
    env_file:
      - .env
    networks:
      - kediritechnopark_network # Hubungkan ke network MinIO

networks:
  kediritechnopark_network:    # Deklarasikan network external
    external: true