version: '3.8'


services:
  astro-app:
    image: kkr-rppi-project:latest
    container_name: kkrppi
    restart: always
    ports:
      - "5476:4321"
    env_file:
      - .env
    # Optional: If you need to mount any local folder (e.g. if the app downloads/backups any local SQLite files)
    # volumes:
    #   - ./data:/app/data
